apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  namespace: ns-{{ .Release.Name }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.hosts }}
      http:
        paths:
          - path: /
            pathType: {{ .Values.pathType }}
            backend:
              service:
                name: {{ .Release.Name }}
                port:
                  number: {{ .Values.exposePort }}