apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: ns-{{ .Release.Name }}
  labels: {{ include "common.labels" . | nindent 4 }}
spec:
  ports:
    - name: {{ .Release.Name }}
      port: {{ .Values.exposePort }}
      targetPort: {{ .Values.targetPort }}
  type: {{ .Values.type }}
  selector: {{ include "common.labels" . | nindent 4 }}